version: 2.1
orbs:
  win: circleci/windows@1.0.0
jobs:
  windows_android_test:
    executor:
      name: win/vs2019
      shell: bash.exe
    steps:
      - checkout:
          path: ~/project
      - restore_cache:
          keys: 
            - android_cache
      - run:
          name: Setup environment variables
          command: |
            echo 'export PATH="$PATH:/usr/local/opt/node@8/bin:${HOME}/.yarn/bin:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin:/usr/local/share/android-sdk/tools/bin"' >> $BASH_ENV
            echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export QEMU_AUDIO_DRV=none' >> $BASH_ENV
            echo 'export JAVA_HOME=/Library/Java/Home' >> $BASH_ENV
            echo 'export PATH="$PATH:`pwd`/flutter/bin"'  >> $BASH_ENV
      - run:
          name: Install Android sdk
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk
      - run:
          name: Install emulator dependencies
          command: (yes | sdkmanager "platform-tools" "platforms;android-26" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;26.0.0" "system-images;android-26;google_apis;x86" "emulator" --verbose) || true
      - run:
          name: chmod permissions
          command: chmod +x ./gradlew
      - run: avdmanager create avd -n Pixel_2_API_26 -k "system-images;android-26;google_apis;x86" -g google_apis -d "Nexus 5"
      - run:
          name: Run emulator in background
          command: /usr/local/share/android-sdk/tools/emulator @Pixel_2_API_26 -noaudio -no-boot-anim -no-window
          background: true
      - run:
          name: download flutter SDK
          command: if ! test -f "flutter_sdk.zip"; then curl -o flutter_sdk.zip https://storage.googleapis.com/flutter_infra/releases/stable/macos/flutter_macos_v1.5.4-hotfix.2-stable.zip; fi
      - run:
          name: unzip flutter SDK
          command: unzip flutter_sdk.zip
      - run: 
          name: Flutter build
          command: cd ..; flutter build aot
      - run:
          name: Download Android Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run UI Tests
          command: ./gradlew app:connectedAndroidTest
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - save_cache:
          key: android_cache
          paths:
            - ~/.gradle
            - flutter_sdk.zip
  danger:
    docker:
      - image: dantoml/danger:latest
    steps:
      - checkout
      - run: danger
  test_module:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}

      - run: yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  test_sample:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - checkout:
          path: ~/project

      - restore_cache:
          key: yarn-v1-{{ checksum "InstabugSample/yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "InstabugSample/package.json" }}-{{ arch }}

      - run: cd InstabugSample && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "InstabugSample/yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "InstabugSample/package.json" }}-{{ arch }}
          paths:
            - InstabugSample/node_modules

      - run:
          name: jest tests
          command: |
            cd InstabugSample
            mkdir -p test-results/jest
            yarn test
          environment:
            JEST_JUNIT_OUTPUT: test-results/jest/junit.xml

      - persist_to_workspace:
          root: ~/project
          paths:
            - InstabugSample/node_modules

      - store_test_results:
          path: InstabugSample/test-results

      - store_artifacts:
          path: InstabugSample/test-results

  test_android:
    working_directory: ~/project/InstabugSample
    docker:
      - image: circleci/android:api-28-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/project
      - run: yarn install
      - run:
          name: chmod permissions
          command: cd android && chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: cd android && ./gradlew androidDependencies
      - run:
          name: Run UnitTest
          command: cd android && ./gradlew test

  test_ios:
    macos:
      xcode: "10.2.0"
    working_directory: ~/project/InstabugSample/ios
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install node_modules
          command: cd .. && yarn
      - run:
          name: Fetch CocoaPods Specs
          command: curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh  | bash -s cf
      - run:
          name: Install CocoaPods
          command: pod install
      - run:
          name: Build and run tests
          command: xcodebuild    -workspace InstabugSample.xcworkspace    -scheme InstabugSample    -sdk iphonesimulator    -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2'    test | xcpretty

  e2e_ios:
    macos:
      xcode: "10.2.0"
    working_directory: ~/project/InstabugSample
    environment:
      FL_OUTPUT_DIR: output
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install React Native CLI
          command: npm install -g react-native-cli
      - run:
          name: Install Detox CLI
          command: npm install -g detox-cli
      - run:
          name: Install Detox Utils
          command: brew tap wix/brew && brew install applesimutils
      - run:
          name: Install node_modules
          command: yarn
      - run:
          name: Fetch CocoaPods Specs
          command: cd ios && curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh  | bash -s cf
      - run:
          name: Install CocoaPods
          command: cd ios && pod install
      - run:
          name: Detox - Build Release App
          command: detox build --configuration ios.sim.release
      - run:
          name: Detox - Run E2E Tests
          command: detox test --configuration ios.sim.release --cleanup

  publish:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: git clone https://InstabugCI:$RELEASE_GITHUB_TOKEN@github.com/Instabug/Escape.git
      - run: cd Escape; swift build -c release -Xswiftc -static-stdlib
      - run: cd Escape/.build/release; cp -f Escape /usr/local/bin/escape
      - run: Escape react-native publish

workflows:
  version: 2
  publish:
    jobs:
      - danger
      - test_module
      - test_sample
      - test_android
      - test_ios
      - windows_android_test
      - hold:
          requires:
            - test_module
            - test_sample
            - test_android
            - test_ios
          type: approval
          filters:
            branches:
              only: master
      - publish:
          requires:
            - hold
          filters:
            branches:
              only: master

